/* ============================================================
   PAPERS — full texts, rendered as readable web pages.

   Nothing here is a download. Each paper opens as its own page
   at #/paper/<id> with its own URL, so it can be linked directly.

   Block types:
     {h:'…'}                     section heading
     {h3:'…'}                    sub-heading
     {p:'…'}                     paragraph
     {list:['…','…']}            bulleted list
     {ol:['…','…']}              numbered list
     {defs:[['USV','…'],…]}      two-column definition list
     {fig:'path', cap:'…'}       figure with caption
     {table:{cap:'…',head:[…],rows:[[…]]}}
     {refs:['…','…']}            numbered reference list
     {note:'…'}                  small aside

   The wording of every paragraph is the author's own and is
   reproduced verbatim from the source documents.
   ============================================================ */

const PAPERS = {

/* ══════════════════════════════════════════════════════════ */
'usv': {
  cat:'medical',
  tab:'Research Papers',
  kicker:'Laboratory Rotation Report · June 2026',
  title:'Analysis of Ultrasonic Vocalization in a Rat Model of Chronic Neuropathic Pain during 3-Chamber Social Paradigm',
  author:'Nicole Bautista Cabral',
  meta:[
    ['Programme','Master in Biomedicine'],
    ['Institution','Universidade do Minho'],
    ['Supervision','Juliana Fiúza-Fernandes · Hugo Leite-Almeida'],
    ['Date','June 2026']
  ],
  abstract:'Chronic pain (CP) carries social and affective consequences that are difficult to quantify in rodent models. Ultrasonic vocalizations (USVs) have been proposed as a proxy of affective state and a coordinator of social interaction. Here we characterized USVs emitted during a three-chamber (3-CH) social paradigm in spared nerve injury (SNI), SHAM and naive Wistar-Han male and female rats, recorded across sociability and social-preference sessions. Calls were identified with DeepSqueak using a 50-kHz custom-trained detector network (RD-V2), selected for its nearest precision and accurate call-contour delimitation. USV parameters (number of calls, call length, principal frequency, bandwidth and sinuosity) were compared by three-way ANOVA across sex, target group and explorer group, with explorer treated as a repeated measure. In the sociability session, the presence of a social partner (Naive vs. Empty) markedly increased the number of calls and their bandwidth, with no significant effect on call length, principal frequency or sinuosity. In the social-preference session, the SNI target side elicited more calls overall, while sex differences and SNI-versus-SHAM differences in call structure (call length, delta frequency, and sinuosity) were male-specific — males emitted longer, broader-bandwidth and more sinuous calls. These findings suggest that USV acoustic structure is sensitive to immediate social context and that pain-associated vocal differences may be sex-dependent, though results are limited by the spatial pooling of calls within chambers, exclusion of 22-kHz detections owing to a high proportion of acoustic artefacts, and the stratified sampling used for network training.',
  keywords:['Ultrasonic vocalizations','chronic pain','spared nerve injury','three-chamber paradigm','DeepSqueak','social behavior'],
  blocks:[
    {h:'List of Abbreviations'},
    {defs:[
      ['3-CH','Three-Chamber (paradigm)'],
      ['AM','Amplitude Modulation'],
      ['Ave','Average'],
      ['CP','Chronic Pain'],
      ['DC','Detected Calls'],
      ['DF','Degrees of Freedom'],
      ['F1','F1 Score'],
      ['FM','Frequency-Modulated (call)'],
      ['FN','False Negative (calls)'],
      ['FP','False Positive (calls)'],
      ['kHz','Kilohertz'],
      ['MPS','Modulation Power Spectra'],
      ['ms','Millisecond'],
      ['P','Precision'],
      ['R','Recall'],
      ['R-CNN','Region-based Convolutional Neural Network'],
      ['RD','Rat Detector YOLO R1 Network (pre-trained built-in network)'],
      ['RD-V1','Rat Detector 1st Custom-Trained Network'],
      ['RD-V2','Rat Detector 2nd Custom-Trained Network'],
      ['REML','Restricted Maximum Likelihood'],
      ['RM','Repeated Measures'],
      ['SEM','Standard Error of the Mean'],
      ['SNI','Spared Nerve Injury'],
      ['SS','Sum of Squares'],
      ['STFT','Short-Time Fourier Transform'],
      ['TP','True Positive (calls)'],
      ['USV','Ultrasonic Vocalization']
    ]},

    {h:'Introduction'},
    {p:'Chronic pain (CP) affects 20% to 30% of the world population, which is frequently compounded by social and emotional adverse effects [1,2]. This is thought to limit translational research as it remains challenging to study in rat models [2,3]. In this regard, ultrasonic vocalization (USV) analysis has been proposed as a reliable proxy of positive and negative emotional responses in rats, and a coordinator of social interactions between them [4]. Ultrasonic vocalizations (USVs) are frequency-modulated calls that range from 20 to 100 kHz, beyond the human hearing range [4,5,6]. These frequency-modulated calls are not random noises, they are triggered across a broad spectrum of behavioral and social contexts: mother-infant interactions [7,8], play behavior [9,10], sexual behavior [11,12], predator exposure [13,14], and during defensive, aggressive, or social conflict situations [14,15].'},
    {p:'Young and adult rats emit USVs that can be categorized into two types of calls namely, “22-kHz” which is recognized as negative or aversive calls and “50-kHz” as positive or appetitive calls, which both served as a readout of the animal’s internal affective state [4]. The sound frequency in the 50-kHz USVs family is between 35 to 85-kHz, which is linked to social engagement and appetitive stimuli. There are at least two primary types of appetitive calls: (1) flat calls, which serve as social coordinators, and (2) frequency modulated (FM) calls, which include step, mixed, and trill calls that are primarily associated with hedonistic and rewarding circumstances [16,17,18]. Some of these rewarding circumstances include social play or mating, and these may even provoke other rats to approach each other [19,20]. On the contrary, the sound frequency in the 22-kHz USVs family is between 20 to 35-kHz [4]. Although rat USVs have primarily developed for social communication, they are also produced in situations that lack any social component [4]. Rats emit long-duration 22 kHz calls in response to aversive non-social stimuli, such as air puffs, loud sounds, and noxious stimulation [4,21,22]. Therefore, when rats are subject to danger or undergo distress, such as upon social defeat or withdrawal from drugs, they emit 22-kHz calls that act as alarm signals to conspecifics, causing them to display signs of anxiety [14,18]. But both 22 kHz and 50 kHz calls are similarly emitted in anticipation of non-social aversive or rewarding events, including food delivery, foot shock, and intracranial self-stimulation [4,23,24,25].'},
    {p:'Several studies have used USVs to capture the emotional component of CP, despite contrasting findings. For example, a rat model of trigeminal neuropathic pain showed reduced 50 kHz calls, interpreted as a loss of appetitive expression, with both local lidocaine and carbamazepine restoring vocal output independently of anxiolysis [16]. A related study attributed these reductions with decreased levels of mesolimbic dopaminergic markers and hyperalgesia [2]. In sciatic nerve injury models, animals also display reduced 50 kHz and increased 22 kHz calls along with fragmented circadian activity, which corresponds to reduced reward and negative effects [26]. However, a multi-model study spanning acute, chronic, inflammatory, and neuropathic pain found broad suppression of both 22 and 50 kHz calls, with analgesics reversing these deficits regardless of pain origin [27]. Reviews further emphasize that 50 kHz changes are particularly informative for the affective dimension of chronic pain [4]. Conversely, some inflammatory and arthritic models report no USV differences between pain and control animals in social settings, highlighting the methodological and model-dependent nature of these effects [28].'},
    {p:'In this study, we aim to characterize ultrasonic vocalizations emitted by spared nerve injury (SNI) and SHAM-surgical control rats which served as target interactors during a three-chamber (3-CH) social paradigm. This paradigm allows simultaneous recording of both SNI and SHAM animals while assessing the social approach of an explorer animal. Thereby, we aim to assess chronic neuropathic pain impact in the expression of USV, both in a quantitative and qualitative manner.'},

    {h:'Aims'},
    {p:'CP alters social behavior and affective processing, which may be reflected in changes in USV patterns during social interaction. Prior studies have shown that rodent USVs serve as markers of emotional state, social motivation, and communicative behaviors [4,19,20,28]. In the context of the three-chamber (3-CH) social paradigm, the characterization of USVs may provide insight into the socio-affective consequences of SNI. Based on these observations, this study aimed to:'},
    {ol:[
      'Accurately detect USV emitted by the rats during the 3-CH paradigm, both in sociability and social preference contexts.',
      'Characterize the USV emitted by the SNI, SHAM and naive rats during the 3-CH paradigm.',
      'Determine whether neuropathic pain is associated with alterations in the quantity, frequency, duration, and other descriptive parameters of vocalizations associated with social behaviors.'
    ]},

    {h:'Materials and Methods'},
    {h3:'1. Experimental Design – Behavioral paradigm'},
    {p:'USVs analyzed in this work were obtained in a previously conducted experiment which examined the effects of neuropathic pain on social behavior of adult male and female Wistar-Han rats during the three-chamber (3-CH) paradigm. The 3-CH consists of a 150 x 50 x 50 cm black plexiglass arena which is symmetrically divided into 3 compartments by a 12 cm-large corridor as shown in Figure 1 below.'},
    {fig:'assets/papers/usv-fig1.jpg', cap:'Figure 1 – Sociability Session and Social Preference Session in 3-CH Paradigm'},
    {p:'In the 2 side chambers, there were perforated transparent walls that created a triangular compartment, where target animals can be placed during social tests. The 3-CH test took place 9 weeks after the SHAM and SNI surgery. Prior to the test, explorer animals were habituated in 2 sessions of 10 minutes each, 2 days apart, where they were placed in the central arena and allowed to freely explore the whole chamber. In target animals, they were habituated to the side chambers in one habituation session, wherein they were placed inside the triangular compartment of each side chamber for 5 minutes.'},
    {p:'Explorer animals are rats subjected to either SHAM or SNI surgery. Target animals are SHAM, SNI or naive rats (without surgical manipulation). The 3-CH test comprises 2 sessions, performed in consecutive days:'},
    {ol:[
      'the sociability session, where a naïve unfamiliar conspecific (no prior surgical procedure) was placed in one of the two side chambers and the other remained empty, while the explorer rat was introduced into the central arena and allowed to explore freely for 10 minutes;',
      'the social preference session, where one target SNI and one target SHAM same-sex unfamiliar conspecific were each placed in one of the two side chambers, while the explorer rat (either SHAM or SNI) was placed in the central arena and allowed to freely explore for 10 minutes.'
    ]},
    {h3:'2. Ultrasonic vocalizations (USVs) recording'},
    {p:'USVs were recorded using two microphones (CM16 Ultrasound Gate, Avisoft Bioacoustics, Germany), each one mounted above the lateral chamber in order to capture the USVs of male and female Wistar-Han rats on the left and right side of the chamber. Microphones were connected to an UltraSoundGate 416H (Avisoft Bioacoustics, Germany) and recorded using the Avisoft-RECORDER USGH software (v.4.4.2-29) [29]. Audio recording is triggered by an Arduino custom-programmed to simultaneously turn on an LED light placed in the outer part of the chamber wall, visible in the video for behavioral analysis. Audio files were saved in .wav format for further analysis.'},
    {h3:'3. Ultrasonic vocalizations (USVs) analysis'},
    {p:'USVs were processed in a five-week pipeline using DeepSqueak as illustrated in Figure 2, a deep-learning based toolbox for MATLAB R2020 (MathWorks, USA) [30]. DeepSqueak converts the audio outputs into short-time Fourier transform (STFT) spectrogram images and applies a region-based convolutional neural network (R-CNN; YOLO architecture) trained on rodent USVs to perform call detections within the spectrogram [30].'},
    {h3:'4. Call Detections'},
    {p:'Calls were initially detected using DeepSqueak\'s pre-trained YOLO networks: the Rat Detector YOLO R1 and the Long Rat Detector YOLO R1. The total analysis length was set to 600s in order to process the full duration of each test session. The detection score threshold was set to 0 to retain all candidate detections for review. The two detection networks were run separately for each audio file to optimize the frequency band for each call type. RD was set with standard settings (600s length, minimum frequency: 35 kHz, maximum frequency: 95 kHz), while LRD with standard settings (analysis length = 600, minimum frequency: 10 kHz, maximum frequency: 35 kHz) [31].'},
    {p:'Similarly, a custom-trained network, RD_V2 (see below), was run to detect calls with standard settings (analysis length = 600, minimum frequency: 10 kHz, maximum frequency: 150 KHz, score threshold = 0) in batch detect mode. USV-related parameters were then exported to excel for further analysis.'},
    {h3:'5. Network training'},
    {p:'In order to improve call detections, we assembled a training dataset from 8 candidate audio files, to ensure diversity of noise profiles and call densities, as well as stratified representation sex of the target animal and social context within the sample. In each candidate audio file, four 1 minute-long segments were manually trimmed from their raw audio files, yielding a total of 16 audio segments. Rat Detector YOLO R1 network (RD) was run for each of these 16 segments to detect calls (analysis length = 0, minimum frequency: 10 kHz, maximum frequency: 150 KHz, score threshold = 0). The detections were then manually reviewed, rejecting false positive calls (Figure 2), and redrawing the area around the selected calls whenever it did not include the full extension of a call. To prevent observer bias, the researcher carrying this review was blind to experimental groups (SNI vs. SHAM; Naive vs Empty). Then, training images were created based on this selection and used to train the RD network, using default DeepSqueak parameters, including iterative exposure of the network to positive detections and false positives to improve classification accuracy [30]. The resulting network was named RD_V1. A second training process was carried out in a similar manner, but using 16 additional segments from the same audio candidates, to increase the acoustic diversity of USV calls. Thus, the training of RD_V1 gave rise to the RD_V2 network.'},
    {fig:'assets/papers/usv-fig2.jpg', cap:'Figure 2 – Representative spectrograms of manually reviewed USV detections used as training data for the custom detector networks RD-V1 and RD-V2'},
    {h3:'6. Network performance assessment'},
    {p:'To qualitatively and quantitatively assess network performance, the 3 networks were run in a validation set comprised of 4 candidate audio recordings (T02, T014, T024, T044) each having 1-minute segments that were randomly extracted from the original audio files. These segments were balanced across groups for a representative sample. True positives (TP), false positives (FP) and false negatives (FN) were then quantified in this validation dataset, and precision [TP/(TP+FP)], and recall [TP/(TP+FN)], were calculated, together with F1 score [2 × Precision × Recall / (Precision + Recall)], which is a balanced metric between precision and recall.'},
    {h3:'7. Statistical analysis'},
    {p:'Statistical analyses and graphical representations were performed using GraphPad Prism 11.0.2 for Windows (GraphPad Software, Boston, Massachusetts USA) [4]. Three-way analysis of variance (ANOVA) was used to compare each USV-related parameter across factors (sex, target animal group and explorer animal group). Since the explorer animal was the same within each session, this factor was treated as repeated measures. Post-hoc comparisons were performed using Sidak-Holm’s correction for multiple testing. Results were considered statistically significant if p&lt;0.05. Figure 3 presents a schematic timeline of USV detection and analysis:'},
    {fig:'assets/papers/usv-fig3.jpg', cap:'Figure 3 – Schematic timeline of USV detection and analysis'},

    {h:'Results'},
    {h3:'1. Exclusion of the Long Rat Detector (22-kHz) network'},
    {p:'The Long Rat Detector YOLO R1 network was designed to detect long 22 kHz calls [30]. However, the detection outputs displayed poor amplitude modulation in the spectrogram as shown in Figure 4. These detections were different from the typical long 22-kHz USVs patterns reported across existing studies [14,21,32,33,34], wherein they are spectrally defined traces of sustained calls within 18 to 35 kHz. In our samples, the detections last longer than 3000 millisecond (ms), which was beyond what was previously described [14,21,34]. Thus, we considered these detections to be noise and excluded the Long Rat Detector YOLO R1 from our analysis pipeline, since, by visual inspection we did not observe any of these calls, and proceeding without confident classification would compromise the validity of subsequent findings.'},
    {fig:'assets/papers/usv-fig4.jpg', cap:'Figure 4 – Representative spectrogram of 22 kHz USV detections using built-in Long Rat Detector YOLO R1'},
    {p:'RD network was used for the detection of short 50 kHz calls. By visual inspection of the detection outputs, we observed a similar large number of false positives, as shown in Figure 5.'},
    {fig:'assets/papers/usv-fig5.jpg', cap:'Figure 5 – Representative spectrogram of False Positive calls in 50 kHz USV detections using built-in Rat Detector YOLO R1'},
    {h3:'2. Custom network training (RD-V1 and RD-V2)'},
    {p:'However, we also observed correct detections, as well as true USV calls that were not fully contained in the detected selection. Thus, in order to improve the detections, we proceeded with the training of the RD network with call images from a selection of our audio files (see methods section 5 and 6). This training process resulted in 2 new networks: RD_V1 and RD_V2. Examples of detections from these networks can be observed in Figure 6.'},
    {fig:'assets/papers/usv-fig6.jpg', cap:'Figure 6 – Representative USV comparative detections in each of the four audio candidates. Rows correspond to detection networks: A — Raw Audios (before detection; no network applied); B — RD: Rat Detector YOLO R1 Network (pre-trained built-in network); C — RD-V1: Rat Detector 1st Custom Trained Network; D — RD-V2: Rat Detector 2nd Custom Trained Network. Numbers correspond to — USV calls: 1 — True positive USV detection example; 2 — Positive USV detection but partially captured; 3 — Noise artefact / low-amplitude event; 4 — False negative, i.e. missed USV detection in either RD or RD-V1).'},
    {h3:'3. Network performance assessment and network selection'},
    {p:'Beside this qualitative appreciation of the detected calls, we aimed to quantitatively assess network performance. Thus, network-related metrics for each audio example are summarized in Table 1.'},
    {table:{
      cap:'Table 1 – Quantitative validation of the three detector networks across 4 randomly sampled audio segments. RD — Rat Detector YOLO R1 Network (pre-trained built-in network); RD-V1 — Rat Detector 1st Custom Trained Network; RD-V2 — Rat Detector 2nd Custom Trained Network. DC — Detection Calls; FP — False Positive Calls; FN — False Negative Calls; TP — True Positive Calls. P — Precision; R — Recall; F1 — F1 Score; Ave — Average.',
      head:['Audio','Network','DC','FP','FN','TP','Total','P','R','F1'],
      rows:[
        ['S1','RD','200','6','21','194','221','0.97','0.902','0.934'],
        ['S1','RD-V1','98','0','110','98','208','1','0.471','0.640'],
        ['S1','RD-V2','163','0','52','163','215','1','0.758','0.862'],
        ['S2','RD','228','3','14','225','242','0.986','0.941','0.963'],
        ['S2','RD-V1','60','0','153','111','264','1','0.420','0.592'],
        ['S2','RD-V2','93','0','82','191','273','1','0.699','0.823'],
        ['S3','RD','145','34','7','111','152','0.765','0.940','0.844'],
        ['S3','RD-V1','98','4','61','56','121','0.933','0.478','0.632'],
        ['S3','RD-V2','163','1','22','92','115','0.989','0.807','0.888'],
        ['S4','RD','192','73','45','119','237','0.619','0.725','0.668'],
        ['S4','RD-V1','60','2','104','75','181','0.974','0.418','0.585'],
        ['S4','RD-V2','93','1','51','128','180','0.992','0.715','0.831'],
        ['Ave','RD','—','—','—','—','—','0.836','0.878','0.853'],
        ['Ave','RD-V1','—','—','—','—','—','0.977','0.447','0.613'],
        ['Ave','RD-V2','—','—','—','—','—','0.995','0.745','0.851']
      ]
    }},
    {p:'RD-V2 network demonstrated the most consistent detection performance across validation audios, achieving near-perfect precision (mean = 0.995) with substantially higher recall than RD-V1 (0.745 vs. 0.447). However, F1 metric was similar between RD and RD_V2 (0.0853 vs 0.851), mainly because RD_V2 misses more calls than RD, which results in a lower recall. However, qualitatively, detections from RD_V2 are more accurately contained within the selection area, and since all the USV-related metrics are derived from the contour of the call [6], which is highly influenced by this criterion, this network was selected for further analysis.'},
    {h3:'4. USV parameters during the 3-CH paradigm'},
    {fig:'assets/papers/usv-fig7.jpg', cap:'Figure 7 – Ultrasonic vocalization (USV) parameters during the sociability session of the 3-CH paradigm. A — Number of calls. Three-way ANOVA revealed a significant social stimulus main effect (F(1,15) = 49.1, p < 0.0001); B — Call length (s); C — Principal frequency (kHz); D — Delta frequency (kHz). Three-way ANOVA revealed a significant social stimulus main effect (F(1,15) = 44.93, p < 0.0001); E — Sinuosity (ratio of the call\'s contour length to the straight-line distance between its endpoints, an index of call curvature (higher = more frequency-modulated). Data are presented as mean ± SEM and analyzed by three-way ANOVA (surgery × social stimulus × sex). Abbreviations: SEM – standard error of the mean.'},
    {p:'In the sociability session, the number of emitted USV calls was markedly affected by the target group (F(1,15) = 49.1, p&lt;0.0001, η² = 0.438), with higher number of calls in the naive target chamber compared to the empty chamber. No significant effect of sex (p = 0.354) or explorer group (p = 0.188) was observed, nor significant interactions between factors (Figure 7.A). Similarly, delta frequency was affected by the target (F(1,15) = 44.93, p&lt;0.0001, η² = 0.527), with a wider range of frequencies in the naive target side compared to the empty side (Figure 7.D).'},
    {p:'No statistically significant differences were found regarding call length, principal frequency or sinuosity for any of the factors tested (Figure 7. B, C and E).'},
    {fig:'assets/papers/usv-fig8.jpg', cap:'Figure 8 – Ultrasonic vocalization (USV) parameters during the social preference session of the 3-CH paradigm. A — Number of calls. Three-way ANOVA revealed a significant target group main effect (F(1,15) = 6.913, p = 0.019); B — Call length (s). Three-way ANOVA revealed a significant sex effect (F, a significant target effect (F(1,15) = 4.829, p = 0.0441) and a sex × target interaction (F(1,15) = 12.56, p = 0.0029); C — Principal frequency (kHz); D — Delta frequency (kHz). Three-way ANOVA revealed a significant sex effect (F(1,15) = 5.339, p = 0.0355), a significant target effect (F(1,15) = 26.86, p < 0.001) and a sex × target interaction (F(1,15) = 32.25, p < 0.001); E — Sinuosity. Three-way ANOVA revealed a significant sex effect (F(1,15) = 30.83, p < 0.001), a significant target effect (F(1,15) = 13.24, p = 0.0024) and a sex × target interaction (F(1,15) = 9.517, p = 0.0075). Data is presented as mean ± SEM and analyzed by three-way ANOVA (explorer animal surgery × social stimulus surgery × sex). Statistically significant results from post-hoc comparisons are represented as *p < 0.05, ** p < 0.01, ***p < 0.001.'},
    {p:'In the social preference session, three-way ANOVA revealed that the total number of USVs was higher in the SNI target side of the 3-CH, regardless of the group and sex of the explorer (significant target effect, F(1,15) = 6.913, p = 0.019). No significant effect of sex or explorer group and no significant interactions were observed (Figure 8.A).'},
    {p:'Regarding call length, females emitted overall shorter calls than males (main sex effect, F(1,15) = 12.39, p = 0.0031, η² = 0.316). Moreover, USV captured in the SNI target side were longer than those of SHAM side (main target effect, F(1,15) = 4.829, p = 0.0441, η² = 0.046), and a significant sex × target interaction was observed (F(1,15) = 12.56, p = 0.0029, η² = 0.120; Figure 8.B). Post-hoc analysis showed that SNI male targets emitted longer USV calls than female SNI, both when the explorer is SHAM (p = 0.0323) and SNI (p = 0.0126) and that, within males, target SNI animals produce longer USV calls when the explorer is also an SNI, compared to a SHAM (p = 0.0474).'},
    {p:'Delta frequency was affected by sex (F(1,15) = 5.339, p = 0.0355, η² = 0.118) and by the target (F(1,15) = 26.86, p&lt; 0.001, η² = 0.185), with a significant sex × target interaction (F(1,15) = p&lt;0.001, η² = 0.222; Figure 8.D). Female calls had an overall lower frequency range than male calls; post-hoc comparisons revealed that this effect is more evident when both explorer and target are SNI animals (p = 0.0038). SNI targets emitted USV with a higher frequency range, an effect driven mainly by male animals (SHAM-SHAM vs SHAM-SNI, p = 0.0014; SNI-SHAM vs SNI-SNI, p = 0.0019)'},
    {p:'Sinuosity is a measure of USV complexity and modulation [30]. Three-way ANOVA showed a significant sex effect (F(1,15) = 30.83, p&lt;0.001, η² = 0.421), with more sinuous calls emitted by males. A significant target effect (F(1,15) = 13.24, p = 0.0024, η² = 0.096), and sex × target interaction (F(1,15) = 9.517, p = 0.0075, η² = 0.069) were also observed (Figure 8.E). Post-hoc analysis showed that, within males, and when the explorer is a SNI, USV calls emitted on the SNI target side were more sinuous than those on the SHAM side (SNI-SHAM vs SNI-SNI, p = 0.0372). Furthermore, female SNI targets under the same conditions emitted less sinuous USV, compared to male SNI (p&lt;0.001).'},
    {p:'No statistically significant differences were found regarding principal frequency (Figure 8.C).'},

    {h:'Discussions'},
    {fig:'assets/papers/usv-fig9.jpg', cap:'Figure 9 – Amplitude modulation (AM) analysis of rat 22-kHz distress vocalisations. (A) Representative oscillograms (top) and spectrograms (bottom) showing weak (left) versus strong (right) AM profiles. (B) Mean modulation power spectra (MPS) of 25 selected vocalisations with strong (top) and weak (bottom) AM. (C) Cliff’s delta effect sizes comparing the strong and weak AM groups. Image from "Amplitude modulation pattern of rat distress vocalisations during fear conditioning," by E. Gonzalez-Palomares, et. al, 2023, Scientific Reports, 13(1), p. 11173. Copyright 2023 by Springer Nature.'},
    {p:'Our findings indicate that 50-kHz calls were shaped mainly by the immediate social context and by sex. In the sociability session, the presence of a naive conspecific increased the number of calls and bandwidth regardless of sex or surgical group, consistent with the role of 50-kHz USVs as appetitive social-contact signals [4,20]. In the social preference session, the differences between groups were carried by call structure and were mostly male-specific, wherein they emitted more, longer, broader-bandwidth calls, including sinuous calls on the SNI target side than on the SHAM side, while the female group showed no modulation. As these effects occurred entirely within the 50-kHz range, the greater bandwidth and sinuosity reflect more frequency-modulated calls, which are linked to heightened positive and social arousal [17,18,35], suggesting a complex 50-kHz calls when a male explorer encountered a conspecific in chronic pain.'},
    {p:'These results contrast with the following studies, where most pain models report reduced 50-kHz calling, interpreted as a loss of appetitive expression, in trigeminal [2,16] and sciatic nerve injury [26], and across multiple pain types [27], while some inflammatory models show no differences [28]. Our findings of increased modulated USVs on the SNI side therefore diverge from these reports, although elevated 50-kHz calls have been reported in early-stage SNI mice [36]. This divergence likely reflects the social nature of our paradigm, as previous studies recorded isolated animals, whereas here the SNI animal was a social target being approached. The male-specificity is consistent with known sexual differences in rat USVs, where males emit longer, more frequency-modulated calls [37,38]; nonetheless, the sex × target interaction suggests that pain-related USV changes may be sex-dependent, reinforcing the need to include both sexes in USV-based pain research.'},
    {p:'The 22-kHz detections by the Long Rat Detector YOLO R1 were excluded from analysis, as they did not closely match true 22-kHz calls. Although long 22-kHz calls typically last more than 300 ms to 2500 ms or up to 3300 to 3400 ms [21,39], which has also shown in highly aversive contexts such as predator odour or fear conditioning [40], our 22-kHz detection results (Figure 4) appeared poorly defined, raising uncertainty as to whether the detected events represented true USVs or false positives. Since it lacked the continuous, flat spectral morphology of true 22-kHz USVs, we therefore treated them as artefacts. True 22-kHz calls are acoustically complex, carrying amplitude modulations (AMs) of 3–100 Hz that vary with affective state (shown in Figure 9) [40]. Since AM was not quantified here, future work should apply validated AM-analysis pipelines, stricter duration and frequency filtering of the detector output, and optimised recording conditions to establish whether true 22-kHz calls occur under the SNI paradigm.'},
    {p:'The 3-CH paradigm offers an ethologically grounded, non-invasive way to probe the social dimension of chronic pain [4,41,42,43,44,45]. Nonetheless, apart from 22-kHz as our primary limitation, several limitations still apply. For instance, DeepSqueak performs human-quality detection even under noise [30], a custom network\'s performance depends on its training and test files, which should be sampled randomly but stratified across sex, surgical group and session, and benchmarked against a manually annotated, group-balanced ground truth (precision, recall and F1) to expose phenotype-specific bias; the lack of an explorer-pain effect should therefore be read as a consequence of unreliable detections (Figure 4) rather than firm evidence of absence. Given that the 50-kHz USV calls index a positive, appetitive affective state and accompany social interaction, and vary inter-individually in number, peak frequency, duration and frequency modulation, splitting it into sociability and preference sessions separates the effect of a partner\'s mere presence from its pain status [34,46]. However, the paradigm is also spatially limited, as calls were pooled across each side chamber per session, so a call cannot be tied to a specific moment of social proximity nor assigned unambiguously to the explorer rather than the confined target, and the empty or naive and SHAM or SNI contrasts co-vary with novelty and odour cues.'},
    {p:'Future work should resolve USV calls by the explorer\'s position relative to the target, pairing call timestamps with tracking data to separate calls emitted during social contact from those of the target alone, thereby clarifying the explorer\'s contribution to the detected calls. Extending the analysis to amplitude modulation and the 22-kHz band [40] and to finer 50-kHz subtype classification [35], in larger, sex-balanced and longitudinal samples, would further clarify any distress signature not captured by the present frequency-domain measures [36].'},

    {h:'References'},
    {refs:[
      'De Ridder D, et al. The anatomy of pain and suffering in the brain and its clinical implications. Neurosci Biobehav Rev. 2021;130:125-146. doi:10.1016/j.neubiorev.2021.08.013',
      'Araya EI, Carvalho EC, Andreatini R, Zamponi GW, Chichorro JG. Trigeminal neuropathic pain causes changes in affective processing of pain in rats. Mol Pain. 2022;18:17448069211057750. doi:10.1177/17448069211057750',
      'Porreca F, Navratilova E. Reward, motivation, and emotion of pain and its relief. Pain. 2017;158(suppl 1):S43-S49. doi:10.1097/j.pain.0000000000000798',
      'Simola N, Granon S. Ultrasonic vocalizations as a tool in studying emotional states in rodent models of social behavior and brain disease. Neuropharmacology. 2019;159:107420. doi:10.1016/j.neuropharm.2018.11.008',
      'Heffner HE, Heffner RS. Hearing ranges of laboratory animals. J Am Assoc Lab Anim Sci. 2007;46(1):20-22.',
      'MacDonald T, Brudzynski SM. Ultrasonic vocalizations, their recording, and bioacoustic analysis. Handb Behav Neurosci. 2018;25:7-19. doi:10.1016/B978-0-12-809600-0.00002-0',
      'Hofer MA. Multiple regulators of ultrasonic vocalization in the infant rat. Psychoneuroendocrinology. 1996;21(2):203-217.',
      'Kaidbey JH, Ranger M, Myers MM, et al. Early life maternal separation and maternal behaviour modulate acoustic characteristics of rat pup ultrasonic vocalizations. Sci Rep. 2019;9(1):1-10.',
      'Kisko TM, Wöhr M, Pellis VC, Pellis SM. From play to aggression: high-frequency 50-kHz ultrasonic vocalizations as play and appeasement signals in rats. Soc Behav Rodents Humans. 2015:91-108.',
      'Knutson B, Burgdorf J, Panksepp J. Anticipation of play elicits high-frequency ultrasonic vocalizations in young rats. J Comp Psychol. 1998;112(1):65-73.',
      'Barfield RJ, Auerbach P, Geyer LA, McIntosh TK. Ultrasonic vocalizations in rat sexual behavior. Am Zool. 1979;19(2):469-480.',
      'Börner A, Hjemdahl R, Götz T, Brown GR. Ultrasonic vocalizations of female Norway rats (Rattus norvegicus) in response to social partners. J Comp Psychol. 2016;130(1):76-80.',
      'Blanchard RJ, Blanchard DC, Agullana R, Weiss SM. Twenty-two kHz alarm cries to presentation of a predator, by laboratory rats living in visible burrow systems. Physiol Behav. 1991;50(5):967-972.',
      'Bonauto SM, Greuel OM, Honeycutt JA. Playback of rat 22-kHz ultrasonic vocalizations as a translational assay of negative affective states: an analysis of evoked behavior and brain activity. Neurosci Biobehav Rev. 2023;153:105396. doi:10.1016/j.neubiorev.2023.105396',
      'Burgdorf J, Kroes RA, Moskal JR, Pfaus JG, Brudzynski SM, Panksepp J. Ultrasonic vocalizations of rats (Rattus norvegicus) during mating, play, and aggression: behavioral concomitants, relationship to reward, and self-administration of playback. J Comp Psychol. 2008;122(4):357-367. doi:10.1037/a0012889',
      'Araya EI, Baggio DF, Koren LO, Schwarting RKW, Chichorro JG. Trigeminal neuropathic pain reduces 50-kHz ultrasonic vocalizations in rats, which are restored by analgesic drugs. Eur J Pharmacol. 2022;920:174854. doi:10.1016/j.ejphar.2022.174854',
      'Brudzynski SM. Pharmacology of ultrasonic vocalizations in adult rats: significance, call classification and neural substrate. Curr Neuropharmacol. 2015;13(2):180-192. doi:10.2174/1570159X13999150210141444',
      'Wöhr M, Schwarting RKW. Affective communication in rodents: ultrasonic vocalizations as a tool for research on emotion and motivation. Cell Tissue Res. 2013;354(1):81-97. doi:10.1007/s00441-013-1607-9',
      'Hammond T, et al. Feel-good songs: application of a novel playback paradigm to induce a positive affective state in juvenile male Wistar rats. Appl Anim Behav Sci. Published online 2024:106296. doi:10.1016/j.applanim.2024.106296',
      'Wöhr M, Schwarting RKW. Ultrasonic communication in rats: appetitive 50-kHz ultrasonic vocalizations as social contact calls. Behav Ecol Sociobiol. 2018;72(1):14. doi:10.1007/s00265-017-2427-9',
      'Brudzynski SM, Holland G. Acoustic characteristics of air puff-induced 22-kHz alarm calls in direct recordings. Neurosci Biobehav Rev. 2005;29(8):1169-1180. doi:10.1016/j.neubiorev.2005.04.007',
      'Oliveira AR, Barros HMT. Ultrasonic rat vocalizations during the formalin test: a measure of the affective dimension of pain? Anesth Analg. 2006;102(3):832-839. doi:10.1213/01.ane.0000196530.72813.d9',
      'Burgdorf J, Knutson B, Panksepp J. Anticipation of rewarding electrical brain stimulation evokes ultrasonic vocalization in rats. Behav Neurosci. 2000;114(2):320-327. doi:10.1037/0735-7044.114.2.320',
      'Kikusui T, Nishizawa D, Takeuchi Y, Mori Y. Conditioned fear-related ultrasonic vocalizations are emitted as an emotional response. J Vet Med Sci. 2003;65(12):1299-1305. doi:10.1292/jvms.65.1299',
      'Tripi JA, Dent ML, Meyer PJ. Individual differences in food cue responsivity are associated with acute and repeated cocaine-induced vocalizations, but not cue-induced vocalizations. Psychopharmacology (Berl). 2017;234(3):437-446. doi:10.1007/s00213-016-4476-6',
      'Burgdorf JS, Ghoreishi-Haack N, Cearley CN, Kroes RA, Moskal JR. Rat ultrasonic vocalizations as a measure of the emotional component of chronic pain. Neuroreport. 2019;30(13):863-866. doi:10.1097/WNR.0000000000001282',
      'Yu Y, Li CL, Du R, Wang XL, Chen J. What do ultrasound vocalizations really mean in rats with different origins of pain? Pain Rep. 2025;10(1):e1230. doi:10.1097/PR9.0000000000001230',
      'Jourdan D, Ardid D, Eschalier A. Analysis of ultrasonic vocalisation does not allow chronic pain to be evaluated in rats. Pain. 2002;95(1):165-173. doi:10.1016/S0304-3959(01)00394-3',
      'Schwarting RKW. Behavioral analysis in laboratory rats: challenges and usefulness of 50-kHz ultrasonic vocalizations. Neurosci Biobehav Rev. 2023;152:105260. doi:10.1016/j.neubiorev.2023.105260',
      'Coffey KR, Marx RG, Neumaier JF. DeepSqueak: a deep learning-based system for detection and analysis of ultrasonic vocalizations. Neuropsychopharmacology. 2019;44(5):859-868. doi:10.1038/s41386-018-0303-6',
      'Popik P, Cyrano E, Golebiowska J, Malikowska-Racia N, Potasiewicz A, Nikiforuk A. Deep learning algorithms reveal increased social activity in rats at the onset of the dark phase of the light/dark cycle. PLoS One. 2024;19(11):e0307794. doi:10.1371/journal.pone.0307794',
      'Narihara I, Yokoyama H, Namba H, et al. Increased self-triggered vocalizations in an epidermal growth factor-induced rat model for schizophrenia. Sci Rep. 2022;12:12917. doi:10.1038/s41598-022-17174-3',
      'Fendt M, Brosch M, Wernecke KEA, et al. Predator odour but not TMT induces 22-kHz ultrasonic vocalizations in rats that lead to defensive behaviours in conspecifics upon replay. Sci Rep. 2018;8:11041. doi:10.1038/s41598-018-28927-4',
      'Berz AC, Wöhr M, Schwarting RKW. Response calls evoked by playback of natural 50-kHz ultrasonic vocalizations in rats. Front Behav Neurosci. 2022;15:812142.',
      'Wright JM, Gourdon JC, Clarke PBS. Identification of multiple call categories within the rich repertoire of adult rat 50-kHz ultrasonic vocalizations. Psychopharmacology (Berl). 2010;211(1):1-13.',
      'Kurejova M, et al. An improved behavioural assay demonstrates that ultrasound vocalizations constitute a reliable indicator of chronic cancer pain and neuropathic pain. Mol Pain. 2010;6:18.',
      'Lenell C, Broadfoot CK, Schaen-Heacock NE, Ciucci MR. Biological and acoustic sex differences in rat ultrasonic vocalization. Brain Sci. 2021;11(4):459.',
      'Tivey EKL, Martin JE, Brown SM, Bombail V, Lawrence AB, Meddle SL. Sex differences in 50 kHz call subtypes emitted during tickling-induced playful behaviour in rats. Sci Rep. 2022;12:15323.',
      'Brudzynski SM. Principles of rat communication: quantitative parameters of ultrasonic calls in rats. Behav Genet. 2005;35:85-92. doi:10.1007/s10519-004-0858-3',
      'Gonzalez-Palomares E, Boulanger-Bertolus J, Dupin M, et al. Amplitude modulation pattern of rat distress vocalisations during fear conditioning. Sci Rep. 2023;13:11173. doi:10.1038/s41598-023-38051-7',
      'Guoynes CD, Pavalko G, Sidorov MS. Courtship and distress ultrasonic vocalizations are disrupted in a mouse model of Angelman syndrome. Research Square. Preprint posted online 2025. doi:10.21203/rs.3.rs-5953744/v1',
      'Jabarin R, Netser S, Wagner S. Beyond the three-chamber test: toward a multimodal and objective assessment of social behavior in rodents. Mol Autism. 2022;13:41. doi:10.1186/s13229-022-00521-6',
      'Keesom SM, Finton CJ, Sell GL, Hurley L. Early-life social isolation influences mouse ultrasonic vocalizations during male-male social encounters. PLoS One. 2017;12(1):e0169705. doi:10.1371/journal.pone.0169705',
      'Martínez-Torres S, Gomis-González M, Navarro-Romero A, Maldonado R, Ozaita A. Use of the Vsoc-maze to study sociability and preference for social novelty in rodents. Bio Protoc. 2019;9(20):e3393. doi:10.21769/bioprotoc.3393',
      'Moy S, Nadler JJ, Perez A, et al. Sociability and preference for social novelty in five inbred strains: an approach to assess autistic-like behavior in mice. Genes Brain Behav. 2004;3(5):287-302. doi:10.1111/j.1601-1848.2004.00076.x',
      'Seidisarouei M, et al. 50-kHz ultrasonic vocalizations do not signal social anhedonia in transgenic DISC1 rats. Brain Behav. 2023;13(5):e2984.'
    ]}
  ]
},

/* ══════════════════════════════════════════════════════════ */
'attention': {
  cat:'medical',
  tab:'Research Papers',
  kicker:'Review Paper · Universidade do Minho',
  title:'Attention Dysregulation on Default Mode Network Functional Connectivity during Doomscrolling among Gen Z Social Media Users',
  author:'Cabral, Nicole',
  meta:[
    ['Institution','Universidade do Minho'],
    ['Type','Outline proposal and review paper']
  ],
  abstract:'Social media\'s short-form video content strategy has been increasingly doomscrolled by Gen Z users, leading to attention dysregulation effects. Doomscrolling is a distinguished slang term that is a growing, social behavior of excessive scrolling contents within the rapid use of social media platforms [6]. Post-pandemic effects have progressively employed the short-form video phenomenon, to Tiktok, Facebook and Instagram reels. Prior studies have shown increased TikTok usage among children and adolescents based on the cross-sectional study in Greece using TikTok addiction scale; a regression analysis result from 525 college participants were associated to burnout and anxiety by Minghua and Feng\'s studies; and a reduced attention span is linked to excessive social media use among 335 student participants in University of Saudi Arabia that are assessed by Mindful Attention Awareness Scale (MAAS) and Bergen Social Media Addiction Scale (BSMAS) [1, 2, 5]. The continuous consumption of short-form video contents leads to reduced attention span and its difficulty to disengage from social media platforms, thereby prompting cognitive decline and prone to psychopathology conditions such as depression and post-traumatic stress disorder [3, 4, 6]. Here, I hypothesize that doomscrolling short video contents is associated with altered default mode network connectivity, particularly in its interaction with attention-related networks, resulting in decreased alerting efficiency. By assessing this, the review seeks to fill a knowledge gap about underexplored default mode network functional connectivity to attention dysregulation during doomscrolling, and search recommended structure for interventions to mitigate compulsive scrolling.',
  keywords:['default mode network','functional connectivity','short video addiction','doomscrolling','attention dysregulation'],
  blocks:[
    {h:'Outline'},
    {p:'Doomscrolling on Tiktok’s short-form video contents has been increasingly engaged by Gen Z users, leading to reduced attention span and its difficulty to disengage from the application’s consumption. Prior studies have shown that the default mode network (DMN) activation is associated when the digital contents being consumed are more personalized. This was focused on reward-driven contents for engagement, leaving a gap in understanding neural implications on short attention span and compulsive scrolling habits. This study seeks to explore the default mode network’s association with a short attention span during continuous short-form video content exposure. Addressing this gap may provide insights on how internal, self-referential processing interacts with attention networks, thereby determining why Gen Z find it difficult to effectively control their attention when they are exposed to poor digital content strategies that are mostly produced below one minute time-watching.'},

    {h:'Search Term Strategy'},
    {list:[
      '("Default Mode Network"[Mesh]) AND ("Internet Addiction Disorder"[Mesh])',
      '(social media) AND (default mode network)',
      '"excessive short video viewing"',
      'Consider synonymous or closely related terminologies manually: “social media addiction” “short video addiction” “doomscrolling” “Tiktok”'
    ]},
    {p:'2.2 Preference will be given to papers published in journals with an established impact factor and CiteScore, but not necessarily excellent but is considered a good score, indicating sustained citation performance and editorial standards within neuroscience domains.'},
    {p:'2.3 Research published in non-indexed or discontinued journals, conference abstracts, editorials, commentaries, or preprints without peer review will be excluded from consideration. To minimize the inclusion of subpar or poorly validated findings, articles from journals with skeptical editorial practices or those without a reported impact factor or CiteScore will be excluded.'},

    {h:'Planned Structure'},
    {ol:[
      'To be able to discuss the Title Concept by Concept: 1. Doomscrolling among Gen Z users 2. Linking to Default Mode Network 3. State the effects “Attention Dysregulation” in default mode network',
      'The root problem and evidence of the test subjects: doomscrolling, scrolling behavior, or excessive consumption of short-form video. Data from the users performing this behaviour',
      'Data about the problem linked to the main concern (brain network): effect of doomscrolling to brain’s default mode network “reduced attention span/attention dysregulation”',
      'Existing studies about addressing solutions/pointing issues about default mode network to social media',
      'Conclusion'
    ]},

    {h:'Main Body'},
    {p:'Doomscrolling is a distinguished slang term that is a growing, social behavior of excessive scrolling across TikTok, Instagram, and Facebook platforms caused by post-pandemic effects [14, 16]. Given that adverse information is constant and pervasive and no amount of information can fully eradicate the predominant feeling of uncertainty during the pandemic, information-seeking behaviour among individuals could prove troublesome [5]. But individuals are more likely to spend more time on digital platforms in an attempt to better their mood when they are feeling low, suffer from decreased interest in activities, and appear to be tired [2]. According to initial reports on the pandemic, a significant number of individuals are consuming COVID-related content on a daily basis, which was a trend known as "doom-scrolling" when one becomes entangled into an endless loop of bad news, and in doing so is linked to poorer mental health [2]. For instance, during the period of lockdowns and stay-at-home orders in many countries, a large cross-sectional survey of over 69,000 college students in France between April and May 2020 revealed that 45% of respondents consumed more than half an hour of pandemic-related informational content daily [2]. Following on these findings, the aim of this review is to explore doomscrolling\'s potential correlation with the brain’s Default Mode Network whether sustained or suppressed in the context of watching short-form videos. Here, we will explore the available data about the potential effects of exposure to short-form videos on self-referential processing, attention dysregulation, and neural network dynamics related to mental fatigue and cognitive control.'},
    {p:'The prevalence of doomscrolling short video consumption up to this day was achieved by tailoring feed based on similar algorithms to maintain Gen Z’s users’ interest to engage through consecutive scrolling [10,12,13]. Many researchers have contextualized this social behaviour as ‘behavioural addiction’ and termed it ‘Short Video Addiction (SVA) [9,10,11,12]. This short video addiction is due to boredom tendency on a broader spectrum of social media, which reported a significant effect on internet-communication disorder [23], problematic Facebook usage [8], problematic mobile social media use [15], and general social network addiction [17]. Several studies have reported that the relationship between boredom tendency [3,8,21,23], problematic use of social networks, and social media are significantly mediated by a variety of psychological factors, including craving [23], desire thinking [17], metacognitions [17], and avoiding negative emotions through online activities [23].'},
    {p:'There is an underlying effect when individuals cannot withhold the urge to scroll in social media. Existing studies conducted a Binge Scrolling Scale (BBS) to examine a significant three-factor structure, in which loss of control over scrolling and negative psychological outcomes were strongly correlated with automatic scrolling [18]. This suggests that more automatic scrolling is linked to greater psychological and physical harm, following poorer self-regulation from doomscrolling behavior [18]. Additional studies have shown increased TikTok usage among children and adolescents based on the cross-sectional study in Greece using TikTok addiction scale; a regression analysis result from 525 college participants were associated to burnout and anxiety by Minghua and Feng’s studies; and a reduced attention span is linked to excessive social media use among 335 student participants in University of Saudi Arabia that are assessed by Mindful Attention Awareness Scale (MAAS) and Bergen Social Media Addiction Scale (BSMAS) [1,4,6,11]. A recent study demonstrated consistent evaluation of problematic short-form video engagement across educational stage and gender, establishing the measurement equivalence of the Problematic Short Video Use Scale (PSVU) between high school and college students [12]. According to the findings, college students report much higher levels of problematic short video use than do high school students [12,15,24,25]. The biggest differences in behavioral change and physiological discomfort are seen in college students, suggesting that increased autonomy and exposure to short-video platforms increase susceptibility [12]. As behavioral markers that may be linked to sustained internally oriented attention, decreased attentional disengagement, and changed Default Mode Network dynamics during excessive short-form video consumption, the identified dimensions of the PSVU capture patterns of compulsive engagement, cognitive and physical strain, and persistent social immersion [12].'},
    {p:'Doomscrolling on short-form videos or remains unclear around the attention dysregulation and their neural substrates. But existing studies mentioned the correlation of alerting, orienting, and executive components of attention and to large-scale resting-state network connectivity [26]. Their study demonstrated results that continuous short video consumption indicated reduced alerting efficiency, implying the inability to focus and maintain attention [26]. This is caused by the functional connectivity between the right ventral prefrontal cortex and right posterior cingulate cortex, and implicating interactions between the control network and default mode network (DMN) [26]. Similarly, Zhai et al. study addressed the effects of short videos on human attention by examining the connections between the default mode network and the brain networks that facilitate attentional regulation [26]. In their study, a Siemens 3 Tesla Prisma scanner with a 64-channel head coil was implemented to gather resting-state functional magnetic resonance imaging data from 115 participants [26]. During the imaging procedure, participants were told to lie on their backs, rest on foam pads to keep their heads upright, keep their eyes open, and refrain from thinking deliberately [26]. Then, time series data were collected for one hundred regions of interest based on a functional brain parcellation that separates the brain into networks such as the default mode network, salience and ventral attention network, limbic network, and control network [26]. After adjusting for age, gender, average head motion, and the short-video addiction score, functional connectivity analysis was evaluated on the connections between each pair of the one hundred brain regions [26]. These significant functional connections have been identified to be concentrated within the default mode network using network-based statistics; the limbic network, control network, salience, and ventral attention network were all involved [26].'},
    {p:'Following further on the default mode network, which includes the medial prefrontal cortex, posterior cingulate cortex, temporal-parietal junction, and temporal pole, suggests to support self-referential and social processing [26]. Whereas the salience and ventral attention network, which includes the right ventral prefrontal cortex and the right temporoparietal junction, prioritizes behaviorally relevant cues and allows for rapid attention reorientation [26]. The right-hemisphere lateralization of ventral prefrontal cortex-posterior cingulate coupling suggests that active short-video engagement biases attentional control toward internal and social processing, reducing readiness to respond to sudden external stimuli and resulting in lower alerting efficiency [26]. Both the frontoparietal network and the core subsystem of the default mode network were tightly coupled, and there was an increase in functional connectivity within the dorsal attention network [26]. These modifications help maintain cognitive control and external attention when watching videos.'},
    {p:'Although recent studies emphasize on the detrimental attention dysregulation of doomscrolling, other research finding suggests that large-scale brain networks related to attention, salience detection, and self-referential processing are systematically modulated by personalized short-video content [19,20]. The dorsomedial prefrontal cortex subsystem is involved in understanding current mental states, mentalizing, social cognition, and semantic comprehension, whereas the ventral attention network identifies novel and behaviorally relevant inputs in a bottom-up approach [19,20]. Enhanced connectivity between these networks is anticipated to enable continuous attention to important video information and self-referential processing, resulting in more immersive experiences with personalized videos [19,20]. In contrast, watching short videos reduced connection between the default mode network\'s core and medial temporal lobe subsystems, implying that engagement with external stimuli lowered spontaneous internal thoughts [19,20]. Additionally, the connection diminished between the salience network and the ventral attention network, indicating that the salience network played a smaller role when active behavioral responses were not required [19,20]. The salience network generally integrates internal and external information and facilitates cognitive control, therefore its lower activation during passive video viewing is consistent with low-demand task conditions [19,20].'},
    {p:'Another study about Fear of Missing Out (FOMO) stated insights on the reduced cortical thickness in core regions of the default mode network due to problematic social media usage [7,22]. This study used a dimensional neuroimaging approach in a student sample to identify a structural brain correlate of fear of missing out, which is centered on the default mode network [22]. Meta-analytic decoding demonstrated that the precuneus region is heavily involved in self-referential processing, social cognition, mentalizing, and autobiographical thought, all of which are indicative of the default mode network [22]. There was no association found between fear of missing out and striatal volume, indicating that fear of missing out is not primarily associated with reward-related brain regions [22]. Instead, the findings suggest that variations in default mode network architecture serve as a neurological substrate for increased sensitivity to social and self-related information [22].'},
    {p:'Based on prior neuroimaging and behavioral findings, we hypothesize that continuous engagement with doomscrolling short video contents is associated with altered default mode network connectivity, particularly in its interaction with attention-related networks, resulting in decreased alerting efficiency. Personalized short videos tend to improve coupling between default mode network areas involved in self-referential processing and attention systems, whereas non-personalized short videos engage externally oriented attention networks more effectively. Active short-video consumption has been linked to lower alerting efficiency, which is mediated by connectivity between control regions and default mode network hubs. Individual differences in social concern and doomscrolling in social media have also been linked to structural and functional variations in core default mode network regions such as the precuneus. These findings imply that persistent exposure to both customized and non-personalized content may change the balance of internally and externally directed attention during continuous scrolling. This imbalance may impose attentional preparedness and contribute to attention dysregulation over time.'},
    {p:'Doomscrolling short videos in social media leads to reduced attention span and its difficulty to disengage from digital platforms, thereby prompting cognitive decline and prone to psychopathology conditions such as depression and post-traumatic stress disorder [gao, li tongshu, price]. Altered default mode network activity has been associated with excessive worry, rumination, and social-cognitive load, suggesting that doomscrolling may increase vulnerability to anxiety, stress, and poor emotional regulation. Furthermore, the majority of research studies are cross-sectional and do not include direct behavioral or physiological measures of attention, which limits causal inferences. Individual variables, such as social media use, personality factors, and social anxiety, are rarely taken into account. Future study should incorporate longitudinal designs, in-scanner behavioral tracking, and the distinction between customized and non-personalized content to further understand how scrolling affects attention and default mode network performance. Understanding these pathways is crucial for implementing strategies to mitigate attentional dysregulation and consolidate solutions on the detrimental doomscrolling behaviour.'},

    {h:'References'},
    {refs:[
      'AlYousef, Noor H, et al. “Does Social Media Addiction Disrupt Mindful Attention of Students in Health Colleges at a University in Saudi Arabia?” Journal of Family and Community Medicine, vol. 32, no. 4, 1 Oct. 2025, pp. 339–346, https://doi.org/10.4103/jfcm.jfcm_223_25. Accessed 31 Oct. 2025.',
      'Anand, Nitin, et al. “Doomsurfing and Doomscrolling Mediate Psychological Distress in COVID‐19 Lockdown: Implications for Awareness of Cognitive Biases.” Perspectives in Psychiatric Care, vol. 58, no. 1, 20 Apr. 2021, https://doi.org/10.1111/ppc.12803.',
      'Baltacı, Önder, and Işılay Açar. “Does Leisure Boredom Predict Short Video Addiction in Adolescents?” Psychiatric Quarterly, 12 June 2025, https://doi.org/10.1007/s11126-025-10172-4.',
      'Bilali, Angeliki, et al. “Association between TikTok Use and Anxiety, Depression, and Sleepiness among Adolescents: A Cross-Sectional Study in Greece.” Pediatric Reports, vol. 17, no. 2, 11 Mar. 2025, pp. 34–34, https://doi.org/10.3390/pediatric17020034.',
      'Buchanan, Kathryn, et al. “Brief Exposure to Social Media during the COVID-19 Pandemic: Doom-Scrolling Has Negative Emotional Consequences, but Kindness-Scrolling Does Not.” PLOS ONE, vol. 16, no. 10, 13 Oct. 2021, p. e0257728, https://doi.org/10.1371/journal.pone.0257728.',
      'Caponnetto, Pasquale, et al. “Does TikTok Addiction Exist? A Qualitative Study.” Health Psychology Research, vol. 13, 6 Jan. 2025, https://doi.org/10.52965/001c.127796.',
      'Chang, Lin, et al. “Linking Self-Concealment to Problematic Short Video Use: Online Social Support and Fear of Missing out as a Serial Mediator.” The Journal of Genetic Psychology, 24 June 2025, pp. 1–13, https://doi.org/10.1080/00221325.2025.2522138.',
      'Donati, Maria Anna, et al. “Boredom and Problematic Facebook Use in Adolescents: What Is the Relationship Considering Trait or State Boredom?” Addictive Behaviors, vol. 125, Feb. 2022, p. 107132, https://doi.org/10.1016/j.addbeh.2021.107132. Accessed 19 Oct. 2021.',
      'Gao, Yuanyuan, et al. “Neuroanatomical and Functional Substrates of the Short Video Addiction and Its Association with Brain Transcriptomic and Cellular Architecture.” NeuroImage, vol. 307, 16 Jan. 2025, p. 121029, https://doi.org/10.1016/j.neuroimage.2025.121029.',
      'Li, Tongshu, et al. “Research Insights on “Problematic Use of Short Video”: A Comprehensive Review Exploration in Psychological Context.” Addiction Biology, vol. 30, no. 11, 1 Nov. 2025, pp. e70082–e70082, https://doi.org/10.1111/adb.70082. Accessed 23 Nov. 2025.',
      'Mao, Minghua, and Feng Liao. “Undergraduates Short Form Video Addiction and Learning Burnout Association Involving Anxiety Symptoms and Coping Styles Moderation.” Scientific Reports, vol. 15, no. 1, 7 July 2025, https://doi.org/10.1038/s41598-025-09656-x.',
      'Mao, Zheng, et al. “Measurement Equivalence and Behavioral Heterogeneity of Problematic Short Video Use: A Cross-Stage and Gender Comparative Study among Adolescents Based on the Physiological-Psychological-Social Model.” Psychological Reports, 15 Oct. 2025, p. 332941251390426, https://doi.org/10.1177/00332941251390426. Accessed 5 Feb. 2026.',
      'Marciano, Laura, et al. “The Developing Brain in the Digital Era: A Scoping Review of Structural and Functional Correlates of Screen Time in Adolescence.” Frontiers in Psychology, vol. 12, no. 12, 27 Aug. 2021, https://doi.org/10.3389/fpsyg.2021.671817.',
      'Muhammed Akat, and Erdal Hamarta. “Doomscrolling and Social Media Addiction in Adolescents: A Two-Wave Longitudinal Study.” Journal of Addictive Diseases, 16 May 2025, pp. 1–9, https://doi.org/10.1080/10550887.2025.2504231.',
      'Pi, Luyang, et al. “An Analysis of the Latent Class and Influencing Factors of Problematic Mobile Social Media Usage among Chinese College Students.” Psychology Research and Behavior Management, vol. Volume 17, Feb. 2024, pp. 367–378, https://doi.org/10.2147/prbm.s438713. Accessed 11 Mar. 2025.',
      'Price, Matthew, et al. “Doomscrolling during COVID-19: The Negative Association between Daily Social and Traditional Media Consumption and Mental Health Symptoms during the COVID-19 Pandemic.” Psychological Trauma: Theory, Research, Practice, and Policy, vol. 14, no. 8, 14 Feb. 2022, https://doi.org/10.1037/tra0001202.',
      'Sara Bocci Benucci, et al. “The Application of the Metacognitive Model of Desire Thinking and Craving in Problematic Social Networking Sites Use.” Psychiatric Quarterly, 21 Oct. 2023, https://doi.org/10.1007/s11126-023-10059-2.',
      'Savci, Mustafa, et al. “The Binge Scrolling Scale Measures Excessive Scrolling through a Validated Three-Factor Structure.” Scientific Reports, 17 Dec. 2025, https://doi.org/10.1038/s41598-025-31861-x. Accessed 17 Dec. 2025.',
      'Su, Conghui, et al. “Individualized Video Recommendation Modulates Functional Connectivity between Large Scale Networks.” Human Brain Mapping, vol. 42, no. 16, 6 Aug. 2021, pp. 5288–5299, https://doi.org/10.1002/hbm.25616. Accessed 1 Dec. 2021.',
      'Su, Conghui, et al. “Viewing Personalized Video Clips Recommended by TikTok Activates Default Mode Network and Ventral Tegmental Area.” NeuroImage, vol. 237, no. 118136, 15 Aug. 2021, p. 118136, https://doi.org/10.1016/j.neuroimage.2021.118136.',
      'Tagliaferri, Ginevra, et al. “Connected by Boredom: A Systematic Review of the Role of Trait Boredom in Problematic Technology Use.” Brain Sciences, vol. 15, no. 8, Aug. 2025, p. 794, https://doi.org/10.3390/brainsci15080794.',
      'Wang, Lan, et al. “Fear of Missing out (FOMO) Associates with Reduced Cortical Thickness in Core Regions of the Posterior Default Mode Network and Higher Levels of Problematic Smartphone and Social Media Use.” Addictive Behaviors, vol. 143, 1 Aug. 2023, p. 107709, https://doi.org/10.1016/j.addbeh.2023.107709. Accessed 19 May 2023.',
      'Wegmann, Elisa, et al. “Is It Beneficial to Use Internet-Communication for Escaping from Boredom? Boredom Proneness Interacts with Cue-Induced Craving and Avoidance Expectancies in Explaining Symptoms of Internet-Communication Disorder.” PLOS ONE, vol. 13, no. 4, 19 Apr. 2018, p. e0195742, https://doi.org/10.1371/journal.pone.0195742.',
      'Ye, Jian-Hong, et al. “Predicting the Learning Avoidance Motivation, Learning Commitment, and Silent Classroom Behavior of Chinese Vocational College Students Caused by Short Video Addiction.” Healthcare, vol. 11, no. 7, 1 Jan. 2023, p. 985, https://doi.org/10.3390/healthcare11070985.',
      'Ye, Jianhong, et al. “The Association of Short-Video Problematic Use, Learning Engagement, and Perceived Learning Ineffectiveness among Chinese Vocational Students.” Healthcare, vol. 11, no. 2, 5 Jan. 2023, pp. 161–161, https://doi.org/10.3390/healthcare11020161.',
      'Zhai, Guanghui, et al. “The Sacrifice of Alerting in Active Short Video Users: Evidence from Executive Control and Default Mode Network Functional Connectivity.” Neuropsychologia, Oct. 2025, p. 109291, https://doi.org/10.1016/j.neuropsychologia.2025.109291. Accessed 6 Oct. 2025.'
    ]}
  ]
},

/* ══════════════════════════════════════════════════════════ */
'antimalarial': {
  cat:'medical',
  tab:'Presentations',
  kicker:'Poster Presentation · ICVS, Universidade do Minho',
  title:'Evaluation of Antimalarial Activity in Plasmodium falciparum',
  author:'Nicole Cabral¹²,  Beatriz Velosa da Fonseca¹²,  Maria Isabel Veiga¹²',
  meta:[
    ['Affiliation 1','Life and Health Sciences Research Institute (ICVS), School of Medicine, University of Minho, Braga, Portugal'],
    ['Affiliation 2','ICVS/3B’s – PT Government Associate Laboratory, Braga/Guimarães, Portugal']
  ],
  poster:{img:'assets/papers/antimalarial-poster.jpg', alt:'Poster: Evaluation of Antimalarial activity in Plasmodium falciparum'},
  blocks:[
    {h:'Introduction'},
    {p:'Despite decades of global intervention, malaria caused an estimated 282 million cases and 610,000 deaths in 2024 (WHO World Malaria Report 2025), with Plasmodium falciparum resistance to artemisinin-based therapies and shortage of drug treatments need urgent attention [1,3]. As a result, Portugal remain vulnerable to imported malaria from tourists and migrants returning from sub-Saharan Africa, Asia, and South America, with 81.5% of infections [2]. Evaluating antimalarial compounds requires in-vitro maintenance of P. falciparum, sustaining asexual blood stages in human erythrocytes at 37°C under a low-oxygen atmosphere (3% O₂, 5% CO₂, 92% N₂) in RPMI 1640 medium supplemented with hypoxanthine and human serum [3]. Cultures are kept within an optimal ring-stage range (at 1-2%) with 4% hematocrit to sustain the log-phase growth [3]. In vitro maintenance and parasitemia assessment of the chloroquine-sensitive 3D7 and chloroquine-resistant Dd2 strains provide the basis methods to do susceptibility assays (IC50) that can evaluate novel antimalarial compounds for overcoming drug resistance and promote drug development.'},

    {h:'Aims'},
    {p:'To maintain in vitro culture of Plasmodium falciparum (Dd2 and 3D7), drug susceptibility assay, and monitor parasite growth by parasitemia assessment.'},

    {h:'Methods'},
    {h3:'Parasite culture maintenance [sterile conditions]'},
    {p:'Maintain incubated blood cultures: P. falciparum (3D7 &amp; Dd2 strains). Aspiration of old medium, then assess parasitemia. Add 5 mL MCM. Maintain the 4% hematocrit. Add gas mixture [3% O₂, 5% CO₂, 92% N₂]. Incubation 37°C.'},
    {h3:'Parasitemia assessment'},
    {ol:[
      'After aspirating the culture, add a drop on the slide.',
      'Fix with 100% methanol (10 seconds).',
      'Cover with 10% Giemsa stain (10 to 15 mins).',
      'Identify parasites and the RBCs.',
      'Choose a quadrant in each 4 fields and quantify the parasites.'
    ]},
    {note:'Formula — No. of infected RBCs (parasites) ÷ (4 × Total no. of RBCs) = (n) × 100% = (n%) parasitemia'},
    {h3:'Susceptibility assays'},
    {ol:[
      'IC50 in Rings — 1% hematocrit, 1% parasitemia.',
      'Perform synchronization by 5% sorbitol treatment.',
      'Perform serial dilution of Chloroquine (CQ) drug.',
      'Incubation 37°C for 72 hours.',
      'Add SYBR Green I in the microplate.',
      'Detect parasite growth on microplate reader.'
    ]},

    {h:'Results'},
    {table:{
      cap:'Chloroquine IC50 and resistance index',
      head:['Chloroquine','3D7 IC50 (nM)','Dd2 IC50 (nM)','Resistance index (Dd2 ÷ 3D7)'],
      rows:[
        ['CQ BEA','4.9 ± 0.5','134.6 ± 36.8','~28×'],
        ['CQ HTS','8.2 ± 2.7','270.3 ± 2.1','~33×']
      ]
    }},
    {p:'Chloroquine produced clear dose-dependent killing in both strains. The chloroquine-sensitive 3D7 had low IC50 values (4.9–8.2 nM), while the resistant Dd2 required ~28–33× higher concentrations (134.6–270.3 nM), consistent across two independent runs (R1, R2) and two preparations (BEA, HTS). The no-drug control (MCM) remained at ~100% survival throughout, confirming culture viability. These known resistance patterns validate the assay for screening novel compounds.'},
    {note:'Figure 1 — MCM = no-drug control; CQ BEA, CQ HTS = two chloroquine preparations; R1, R2 = independent replicates.'},

    {h:'Conclusion'},
    {p:'We established in vitro maintenance of P. falciparum with parasitemia assessment and evaluating by drug susceptibility assays. Given malaria\'s persistent global burden [1], such capacity is vital on antimalarial drug further development.'},

    {h:'References'},
    {refs:[
      'World Health Organization. World Malaria Report 2025. World Health Organization; 2025. Serrano D, Santos-Reis A, Silva C, et al. Imported malaria in Portugal: prevalence of polymorphisms in the anti-malarial drug resistance genes pfmdr1 and pfk13. Microorganisms. 2021;9(10):2045. doi:10.3390/microorganisms9102045',
      'Trager W, Jensen JB. Human malaria parasites in continuous culture. Science. 1976;193(4254):673-675. doi:10.1126/science.781840',
      'Delves MJ, Straschil U, Ruecker A, et al. Routine in vitro culture of Plasmodium falciparum gametocytes to evaluate novel transmission-blocking interventions. Nat Protoc. 2016;11(9):1668-1680. doi:10.1038/nprot.2016.096'
    ]}
  ]
}

};
